
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      warning=FALSE,
                      cache = FALSE)
library(tidyverse)
library(lubridate)
library(janitor)
library(stringr)
source("scripts/viridis.R")
```



```{r}

breaks = read.csv("data/Water_Main_Breaks.csv") %>%
  select(OBJECTID,pipe_size,pipe_depth_ft,break_date,break_year)%>%
  drop_na()%>%
  mutate(m=ymd_hms(break_date),
         break_month=month(m))%>%
  mutate(pipe_depth_ft=round_to_fraction(pipe_depth_ft,2,Inf),
         pipe_size=round_to_fraction(pipe_size,2,Inf))%>%
  select(OBJECTID,pipe_size,pipe_depth_ft,break_month,break_year)%>%
  group_by(break_month,break_year,pipe_size,pipe_depth_ft)%>%
  summarize(n=n())%>%
  mutate(pipe_size_3=pipe_size^3,
    pipe_size_2=pipe_size^2,
    pipe_depth_3=pipe_depth_ft^3,
         pipe_depth_2=pipe_depth_ft^2,
         break_year_2=break_year^2,
         linear=1)%>%
  select(pipe_depth_3,pipe_depth_2,pipe_depth_ft,pipe_size_3,pipe_size_2,pipe_size,break_year_2,break_year,linear,n,break_month)

write.csv(breaks,"data/training_matrixv2.csv")

##Forv1, remove the trounding mutate

breaks


```

```{r}

test = read.csv("data/Water_Main_Breaks.csv") %>%
  select(OBJECTID,pipe_size,pipe_depth_ft,break_date,break_year)%>%
  drop_na()%>%
  mutate(m=ymd_hms(break_date),
         break_month=month(m))%>%
  select(OBJECTID,pipe_size,pipe_depth_ft,break_month,break_year)%>%
  mutate(pipe_depth_ft=round_to_fraction(pipe_depth_ft,2,Inf),
         pipe_size=round_to_fraction(pipe_size,2,Inf))%>%
  group_by(break_month,pipe_size,pipe_depth_ft,break_year)%>%
  summarize(n=n())%>%
  filter(break_year==2019|break_year==2018)%>%
  mutate(pipe_size_3=pipe_size^3,
    pipe_size_2=pipe_size^2,
    pipe_depth_3=pipe_depth_ft^3,
         pipe_depth_2=pipe_depth_ft^2,
         linear=1,
         break_year=2021,
    break_year_2=break_year^2)%>%
 subset(select=-c(n))%>%
 select(pipe_depth_3,pipe_depth_2,pipe_depth_ft,pipe_size_3,pipe_size_2,pipe_size,break_year_2,break_year,linear,break_month)

test

write.csv(test,"data/test.csv")

```


```{r}
question=breaks%>%
  group_by(break_year)%>%
  summarize(n=sum(n))
question
```
```{r}
manupilate = read.csv("data/manupilationv2.csv")%>%
            subset(select=-c(X))

manupilate=unique(manupilate)%>%
  mutate(depth=case_when(
    pipe_depth<=5 ~ "3 - 5",
    (pipe_depth>5 & pipe_depth<=8) ~ "5 - 8",
    pipe_depth>8 ~ "8 - 11"
  )) %>%
    mutate(size=case_when(
    pipe_size<=4 ~ "1 - 4",
    (pipe_size>4 & pipe_size<=8) ~ "4 - 8",
    pipe_size>8 ~ "8 - 12"
  ))%>%
  group_by(Month,depth,size)%>%
  summarize(count=sum(Number))%>%
  mutate(count=round(count))%>%
  filter(Month<=3|Month==12)


```


```{r}

ggplot(manupilate,aes(fill=size,x=depth,y=count))+
  geom_bar(position="stack",width=0.7,stat="identity")+
  facet_wrap(~Month)+
  labs(fill="Pipe Size (m)", x="Pipe Depth (ft)",y="Expected Number of Breaks")+
  theme(text = element_text(size=20),
    axis.text = element_text(size=15))

```
```{r}
manupilate = read.csv("data/manupilationv2.csv")%>%
            subset(select=-c(X))

manupilate=unique(manupilate)%>%
  mutate(depth=case_when(
    pipe_depth<=5 ~ "3 - 5",
    (pipe_depth>5 & pipe_depth<=8) ~ "5 - 8",
    pipe_depth>8 ~ "8 - 11"
  )) %>%
    mutate(size=case_when(
    pipe_size<=4 ~ "1 - 4",
    (pipe_size>4 & pipe_size<=8) ~ "4 - 8",
    pipe_size>8 ~ "8 - 12"
  ))%>%
      mutate(season=case_when(
    Month<=2 ~ "Winter",
    (Month>2 & Month<=5) ~ "Spring",
    (Month>5 & Month<=8) ~ "Summer",
    (Month>8 & Month<=11) ~ "Fall",
    Month==12 ~ "Winter"
  ))%>%
  group_by(season,depth,size)%>%
  summarize(count=sum(Number))%>%
  mutate(count=round(count))


```

```{r}
pdf("pipemodel.pdf")
ggplot(manupilate,aes(fill=size,x=depth,y=count))+
  geom_bar(position="stack",width=0.7,stat="identity")+
  facet_wrap(~season)+
  labs(fill="Pipe Size (m)", x="Pipe Depth (ft)",y="Expected Number of Breaks")+
  theme(text = element_text(size=20),
    axis.text = element_text(size=15))
dev.off()

```


```{r, fig.width=4,fig.height=4}
pdf("pipetype.pdf")
ggplot(manupilate,aes(fill=size,x=depth,y=count))+
  geom_bar(position="stack",width=0.7,stat="identity")+
  labs(fill="Pipe Size (m)", x="Pipe Depth (ft)",y="Expected Number of Breaks")+
  theme(text = element_text(size=20),
    axis.text = element_text(size=15))
dev.off()
```

